# conda environment description file for docs build environment
# on readthedocs.org

name: sphinx-build

channels:
  - defaults

dependencies:
- ipython
- jupyter
- matplotlib
- pip
- python=3.5
- pip:
  - nbsphinx
