# conda environment description file for docs build environment
# on readthedocs.org

name: sphinx-build

channels:
  - conda-forge
  - nodefaults

dependencies:
  - ipython
  - jupyter
  - matplotlib
  - pip
  - python=3.13

  # Sphinx and extensions we use
  - nbsphinx==0.9.5
  - sphinx=8.1.3
  - sphinx-rtd-theme=3.0.0

  # readthedocs build system packages
  - mock
  - pillow
  - pip:
    - commonmark
    - recommonmark
    - readthedocs-sphinx-ext
