# conda environment description file for docs build envioronment
# on readthedocs.org

name: sphinx-build

channels:
  - defaults

dependencies:
- ipython
- jupyter_client
- matplotlib
- pip
- python=3.5
- pip:
  - nbsphinx
