# Script for running simple GYRE configuration

#PBS -l procs=1
#PBS -l pmem=500mb
#PBS -l walltime=00:05:00 

module load compiler/intel/12.1
module load library/intelmpi/4.0.3.008
module load library/netcdf/4.1.3
module load library/szip/2.1

module list
echo "Current working directory is `pwd`"
cd dev_v3_4_STABLE_2012/NEMOGCM/CONFIG/NEW_GYRE/EXP00
echo "Current working directory is `pwd`"

echo "Starting run at: `date`"
./opa
echo "Program opa finished with exit code $? at: `date`"
