# conda environment description file for SalishSeaTools package
# development environment
#
# Create a conda environment for development, testing and documentation
# of the SalishSeaTools package with:
#
#   $ cd tools
#   $ conda env create -f SalishSeaTools/environment.yaml
#   $ conda activate salishsea-tools
#   (salishsea-tools)$ python -m pip install --editable SalishSeaTools
#
# See the requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: salishsea-tools

channels:
  - conda-forge
  - nodefaults

dependencies:
- arrow>=1.0.0
- bottleneck
- cliff
- cmocean
- coverage
- f90nml
- gsw
- ipdb
- ipython
- jupyterlab
- lxml
- matplotlib
- nbsphinx
- netCDF4
- numpy
- openpyxl
- pandas
- pip
- pytest
- python=3.12
- pytz
- python-dateutil
- pyyaml
- requests
- retrying
- scipy
- sphinx
- sphinx_rtd_theme
- tqdm
- xarray
- pip:
  - angles
