# conda environment description file for SalishSeaTools package
# development environment
#
# Create a conda environment for development, testing and documentation
# of the SalishSeaTools package with:
#
#   $ cd tools
#   $ conda env create -f SalishSeaTools/environment.yaml
#   $ conda activate salishsea-tools
#   (salishsea-tools)$ python -m pip install --editable SalishSeaTools
#
# See the requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: salishsea-tools

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow>=1.0.0
  - bottleneck
  - cliff
  - cmocean
  - f90nml
  - gsw
  - h5netcdf
  - ipdb
  - ipython
  - jupyterlab
  - lxml
  - matplotlib
  - netCDF4
  - numpy
  - openpyxl
  - pandas
  - pip
  - python=3.12
  - pytz
  - python-dateutil
  - pyyaml
  - requests
  - retrying
  - scipy
  - tqdm
  - xarray

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - nbsphinx==0.9.5
  - sphinx=8.1.3
  - sphinx-rtd-theme=3.0.0

  - pip:
    - angles
