# conda environment description file for SalishSeaCmd package
# development environment
#
# Create a conda environment in which the `salishsea` command can be run
# with:
#
#   $ cd tools
#   $ conda env create -f SalishSeaCmd/environment.yaml
#   $ source activate salishsea-cmd
#   (salishsea-cmd)$ pip install --editable SalishSeaTools
#   (salishsea-cmd)$ pip install --editable SalishSeaCmd
#
# The environment will also include all of the tools used to develop,
# test, and document the SalishSeaCmd package.
#
# See the requirements.pip file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: salishsea-cmd
dependencies:
- coverage
- ipython
- matplotlib
- netCDF4
- numpy
- pandas
- pip
- pytest
- python=3.4
- pytz
- requests
- scipy
- sphinx
- pip:
  - angles
  - arrow
  - cliff
  - ipdb
