# conda environment description file for SalishSeaCmd package
# development environment
#
# Create a conda environment in which the `salishsea` command can be run
# with:
#
#   $ cd tools
#   $ conda env create -f SalishSeaCmd/environment.yaml
#   $ source activate salishsea-cmd
#   (salishsea-cmd)$ pip install --editable SalishSeaTools
#   (salishsea-cmd)$ pip install --editable SalishSeaCmd
#
# The environment will also include all of the tools used to develop,
# test, and document the SalishSeaCmd package.

name: salishsea-cmd
dependencies:
- alabaster=0.7.3=py34_0
- babel=1.3=py34_0
- coverage=3.7.1=py34_0
- curl=7.43.0=1
- decorator=4.0.2=py34_0
- docutils=0.12=py34_0
- fontconfig=2.11.1=4
- freetype=2.5.2=2
- hdf5=1.8.15.1=1
- ipython=4.0.0=py34_0
- ipython_genutils=0.1.0=py34_0
- jinja2=2.8=py34_0
- krb5=1.13.2=0
- libnetcdf=4.3.3.1=1
- libpng=1.6.17=0
- libxml2=2.9.2=0
- markupsafe=0.23=py34_0
- matplotlib=1.4.3=np19py34_2
- netcdf4=1.1.9=np19py34_0
- numpy=1.9.2=py34_0
- openssl=1.0.1k=1
- pandas=0.16.2=np19py34_0
- path.py=7.6=py34_0
- pexpect=3.3=py34_0
- pickleshare=0.5=py34_0
- pip=7.1.0=py34_1
- py=1.4.30=py34_0
- pygments=2.0.2=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.3=py34_1
- pytest=2.7.2=py34_0
- python=3.4.3=1
- python-dateutil=2.4.2=py34_0
- pytz=2015.4=py34_0
- pyyaml=3.11=py34_1
- qt=4.8.6=3
- readline=6.2=2
- requests=2.7.0=py34_0
- scipy=0.16.0=np19py34_0
- setuptools=18.1=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.16.5=py34_0
- six=1.9.0=py34_0
- snowballstemmer=1.2.0=py34_0
- sphinx=1.3.1=py34_0
- sphinx_rtd_theme=0.1.7=py34_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- traitlets=4.0.0=py34_0
- wheel=0.24.0=py34_0
- xz=5.0.5=0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - angles==1.1
  - arrow==0.6.0
  - cliff==1.14.0
  - cmd2==0.6.8
  - ipdb==0.8.1
  - ipython-genutils==0.1.0
  - nose==1.3.7
  - pbr==1.5.0
  - prettytable==0.7.2
  - sphinx-rtd-theme==0.1.7
  - stevedore==1.7.0
  - unicodecsv==0.13.0
