# conda environment description file for SalishSeaCmd package
#
# Create a conda environment in which the `salishsea` command can be run
# with:
#         $ cd tools
#         $ conda env create -f SalishSeaCmd/environment.yaml

name: SalishSeaCmd
dependencies:
- cairo=1.12.18=3
- curl=7.38.0=0
- fontconfig=2.11.1=3
- freetype=2.5.2=0
- hdf5=1.8.14=0
- ipython=3.1.0=py27_0
- libnetcdf=4.3.2=1
- libpng=1.5.13=1
- libxml2=2.9.0=0
- matplotlib=1.4.3=np19py27_1
- mock=1.0.1=py27_0
- netcdf4=1.1.6=np19py27_0
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.0=np19py27_1
- pip=6.1.1=py27_0
- pixman=0.26.2=0
- py=1.4.26=py27_0
- py2cairo=1.10.0=py27_2
- pyparsing=2.0.3=py27_0
- pyqt=4.11.3=py27_1
- pytest=2.7.0=py27_0
- python=2.7.9=2
- python-dateutil=2.4.2=py27_0
- pytz=2015.2=py27_0
- pyyaml=3.11=py27_0
- qt=4.8.6=1
- readline=6.2=2
- setuptools=15.1=py27_1
- sip=4.16.5=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- yaml=0.1.4=0
- zlib=1.2.8=0
- pip:
  - angles==1.1
  - arrow==0.5.4
  - cliff==1.12.0
  - cmd2==0.6.8
  - ipdb==0.8
  - pathlib==1.0.1
  - pbr==0.10.8
  - prettytable==0.7.2
  - stevedore==1.4.0
  - ./SalishSeaCmd
  - ./SalishSeaTools

