# conda environment description file for SalishSeaNowcast package
#
# Create a conda environment in which the `salishsea` command can be run
# with:
#         $ cd tools
#         $ conda env create -f SalishSeaNowcast/environment.yaml

name: nowcast
dependencies:
- alabaster=0.7.3=py27_0
- babel=1.3=py27_0
- cairo=1.12.18=4
- coverage=3.7.1=py27_0
- curl=7.38.0=0
- docutils=0.12=py27_0
- ecdsa=0.11=py27_0
- fontconfig=2.11.1=4
- freetype=2.5.2=2
- hdf5=1.8.14=0
- jinja2=2.7.3=py27_1
- libnetcdf=4.3.2=1
- libpng=1.6.17=0
- libsodium=0.4.5=0
- libxml2=2.9.2=0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np19py27_2
- netcdf4=1.1.8=np19py27_0
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.2=np19py27_0
- paramiko=1.15.2=py27_0
- pip=7.1.0=py27_0
- pixman=0.26.2=0
- py=1.4.30=py27_0
- py2cairo=1.10.0=py27_2
- pycrypto=2.6.1=py27_0
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.3=py27_1
- pytest=2.7.2=py27_0
- python=2.7.10=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.4=py27_0
- pyyaml=3.11=py27_1
- pyzmq=14.7.0=py27_0
- qt=4.8.6=3
- readline=6.2=2
- requests=2.7.0=py27_0
- scipy=0.15.1=np19py27_0
- setuptools=18.0.1=py27_0
- sip=4.16.5=py27_0
- six=1.9.0=py27_0
- snowballstemmer=1.2.0=py27_0
- sphinx=1.3.1=py27_0
- sphinx_rtd_theme=0.1.7=py27_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- yaml=0.1.6=0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - angles==1.1
  - arrow==0.5.4
  - beautifulsoup4==4.4.0
  - cliff==1.13.0
  - cmd2==0.6.8
  - mako==1.0.1
  - mock==1.0.1
  - nose==1.3.7
  - pathlib==1.0.1
  - pbr==1.2.0
  - prettytable==0.7.2
  - sphinx-bootstrap-theme==0.4.7
  - sphinx-rtd-theme==0.1.7
  - stevedore==1.6.0

