# conda environment description file for SalishSeaNowcast package
#
# Create a conda environment for development, testing, and documentation
# of the Salish Sea Nowcast system with:
#
#    $ cd tools
#    $ conda env create -f SalishSeaTools/nowcast/environment.yaml
#    $ source activate nowcast
#    $ pip install --editable SalishSeaTools
#    $ pip install --editable SalishSeaCmd

name: nowcast
dependencies:
- coverage
- ipython
- jupyter
- mako
- matplotlib
- netCDF4
- numpy
- pandas
- paramiko
- pytest
- pyyaml
- pyzmq
- pip
- python=3
- requests
- scipy
- sphinx
- pip:
  - angles
  - arrow
  - BeautifulSoup4
  - ipdb
  - sphinx-bootstrap-theme
