# conda environment description file for SalishSeaTools package
# development environment
#
# Create a conda environment for development, testing and documentation
# of the SalishSeaTools package with:
#
#   $ cd tools
#   $ conda env create -f SalishSeaTools/envs/environment-dev.yaml
#   $ conda activate salishsea-tools
#
# See the envs/requirements.txt file for an exhaustive list of all the
# packages installed in the environment and their versions used in
# recent development.

name: salishsea-tools

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - bottleneck
  - cmocean
  - f90nml
  - gsw
  - h5netcdf
  - ipdb
  - ipython
  - jupyterlab
  - lxml
  - matplotlib
  - netCDF4
  - numpy
  - openpyxl
  - pandas
  - pip
  - python=3.13
  - pytz
  - python-dateutil
  - pyyaml
  - requests
  - retrying
  - scipy
  - tqdm
  - xarray

# For coding style, repo QA, and package management
  - black
  - hatch
  - pre-commit

  # For unit tests
  - coverage
  - pytest-cov
  - pytest-randomly

  # For documentation
  - nbsphinx==0.9.5
  - sphinx=8.1.3
  - sphinx-rtd-theme=3.0.0

  - pip:
    - angles

    # Install the SalishSeaTools packages in editable mode
    - --editable ../
