name: Add Milestone to Issue/PR

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  add_milestone:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/milestone-action@v3
        with:
          # If true, add the milestone with the farthest due date. By default,
          # the action adds the current milestone (the closest due date).
          farthest: false

          # If true, overwrite existing milestones on issues and pull requests.
          # By default, the action exits if a milestone has already been added.
          overwrite: false

          # If true, add the only open milestone in a repo, even if there is no
          # due date. By default, milestones with no due date are ignored.
          single: false
